### ISSUE TITLE
Feature Request - Changing height/width of gallery thumbnails

### ISSUE THREAD

**Issue by aheadzen** [pedroabreu/ion-gallery#12]
Hello,

Thanks for the gallery module, highly useful and easy to use. Would it be possible for you to add an option to resize every 1st, 4th, 8th image etc. ?

We are trying to make it more like facebook timeline where if I upload 1 image, facebook shows as full-width image. If I upload 4 images, facebook will try to resize 1 of them as full width and rest as thumbnails.

If difficult to implement, may be adding an option to use external html template can allow developers to customise as and when required.

Thanks
Arpit

**Comment by pedroabreu** [comment]
I was thinking of changing the row size option to an array, where you could for example define [1,3] and it would loop through it.
Do you have any example of a directive that uses external templates ? It would be interesting to do both, actually

**Comment by aheadzen** [comment]
Hello, thanks for quick response.

I am using external templates with ion autocomplete directive - https://github.com/guylabs/ion-autocomplete#template-url

I am not sure how easy would be doing resizing through array but i think we could take help of this directive from angularjs - https://github.com/mboudreau/angular-mosaic

**Comment by pedroabreu** [comment]
Interesting. I'll have a look at both of the projects and see if I can come up with an idea for this.
Don't be shy to do a PR with these changes :)

**Comment by pedroabreu** [comment]
Fixed with #62
