### ISSUE TITLE
Uncaught ReferenceError: onResize is not defined

### ISSUE THREAD

**Issue by FreshApps** [pedroabreu/ion-gallery#14]
Hi there, 

I did implement everything like it's on readme, but i still got this error. I have looked everywhere it but couldn't find anything. Please help me with this. 

The problem occurs when i click on the image to zoom it in. I get a black model with done button, but the image is not loaded, and also for the subtitle

Regards

**Comment by pedroabreu** [comment]
Can you provide a screenshot ?

**Comment by FreshApps** [comment]
Like i said it happens when i want to click on the picture to open a modal

![screen shot 2015-10-21 at 9 42 25 am](https://cloud.githubusercontent.com/assets/4630044/10630618/28af2a58-77d8-11e5-91a5-9efa5ac5a42f.png)

**Comment by pedroabreu** [comment]
Just to be clear, is this error on mobile or desktop ? Just to be sure if this can be a issue with a click event, instead of using a touch event.

**Comment by FreshApps** [comment]
I uploaded also to a mobile and tested on a desktop but both doesn't show the image. the only thing i am seeing  is a black screen with only DONE button.

**Comment by pedroabreu** [comment]
Missing css file. Closed
