### ISSUE TITLE
Gallery cycle

### ISSUE THREAD

**Issue by alexjoyner** [pedroabreu/ion-gallery#16]
When I create a gallery that has more than 3 images in it, the gallery will only cycle through three images every time I open the gallery.  For example: If I had a gallery that was pictures of a cat, dog, horse, pig, lion, bird, and snake, if I opened a gallery by touching the horse, swiping through the images to cycle would only cycle through the pig, horse, and cat (I didn't notice any patterns in the three images that would open up but it would be the same per image). If I clicked on the snake, the three images might be the snake, cat, and bird.

**Comment by alexjoyner** [comment]
Upon further inspection, I found that the there was a pattern to the 3 images that were being shown in the cycle. It is always the image selected, the image before, and image after.  From the example above: If I selected the dog, the three images would be the cat, dog, and horse...  On the ends, it shows the next image cycled around.  If I selected the cat, it would cycle through the cat, dog, and snake.

**Comment by pedroabreu** [comment]
Didn't get the issue. The slider works with a three image circular buffer, as in, only three images are loaded at the time. This way you can have a 1000 images gallery and still slide trough all of them without having to render all the 1000 images for the slider.

**Comment by alexjoyner** [comment]
I thought I had an updated version of the plugin, but I guess I didn't.  I uninstalled and reinstalled and the issue was resolved.
