### ISSUE TITLE
Feature Request - Show full images on click within slideshow

### ISSUE THREAD

**Issue by w3development-kn** [pedroabreu/ion-gallery#17]
My webservice returns about 100 images as thumbnails with 100x100px. It would be awesome if the original pictures (links returned from the webservice, too) would open on click within the slideshow.

The new data would look like this:

$scope.items = [
  {
    src:'http://www.wired.com/images_blogs/rawfile/2013/11/offset_WaterHouseMarineImages_62652-2-660x440.jpg',
   fullSrc: "http://www.fullimage.de/image.jpg",
    sub: 'This is a <b>subtitle</b>'
  }.....

**Comment by pedroabreu** [comment]
Interesting. So the feature would be opening a "different" image (source) wise. This can be useful for videos, for example, where you load a thumbnail and then open up the video on click. Should be fairly simple to implement.

**Comment by w3development-kn** [comment]
Any chance for this to come in a few days? ;)

**Comment by pedroabreu** [comment]
I've made a PR with this change, by adding the thumbnail property. I will have a think if it makes sense as it is and probably merge it tonight.

Have a look at it as well.

**Comment by w3development-kn** [comment]
Great thank you. Another short question. I´m doing changes to src/templates/gallery.html. But they get not affected in my app. Any ideas why?

**Comment by pedroabreu** [comment]
you need to compile it with gulp (just run 'gulp' on the plugin folder). I assume you're just loading the JS and CSS files in your project, the html is inject in the JS using angular-templatecache.
I'm thinking of a way of allowing custom templates but struggling a bit with it

**Comment by pedroabreu** [comment]
Merged
