### ISSUE TITLE
How can i add additional buttons to the header next to the 'done' button?

### ISSUE THREAD

**Issue by vandervidi** [pedroabreu/ion-gallery#19]
I would like to add additional buttons like 'share' , 'delete' .
How can i do this?

**Comment by pedroabreu** [comment]
As for now you can't but it's definitely something I have in my mind to implement. Although, of course, I'm open to any Pull Request with that feature :)

**Comment by w3development-kn** [comment]
go to ion-gallery/templates/slider.html. 
Before line 3 you can add any button you want.

**Comment by pedroabreu** [comment]
Fixed with #62
