### ISSUE TITLE
Image displays wrong in first line

### ISSUE THREAD

**Issue by w3development-kn** [pedroabreu/ion-gallery#20]
There is a wrong spacing between images in first line.

![bildschirmfoto 2015-11-23 um 13 19 38](https://cloud.githubusercontent.com/assets/1951916/11336403/5637b09a-91e5-11e5-8eae-0224505723bb.png)

Have you seen this error already?

**Comment by pedroabreu** [comment]
Can i get a sample set of those pictures ? (Or at least their dimensions) I can't reproduce the issue with the sample set I use.

**Comment by w3development-kn** [comment]
sorry for the late response. I´m using strictly 200x200px images.
