### ISSUE TITLE
JS error when navigating away from a view that uses ion-gallery without clicking on image

### ISSUE THREAD

**Issue by ggoforth** [pedroabreu/ion-gallery#28]
The specific error is:

<img width="514" alt="screenshot 2015-12-26 09 37 56" src="https://cloud.githubusercontent.com/assets/1167712/12007335/63337a70-abb4-11e5-8f61-d0a1d4e6ea04.png">

In doing some quick digging through the source (well organized, BTW) I _think_ it might be related to the modal code for the image click handling.  

So, if I:
1. Navigate into a view with ion-gallery and DO NOT click on any images in the gallery, I get the above area.
2. Navigate into a view with ion-gallery and DO click on some images, then the error does not happen. 

I can debug more and put together an example, but I think the issue is with line 452 in ion-gallery.js.  When no image is clicked on, `_modal` is undefined, thus calling `remove` yields the error.

**Comment by ggoforth** [comment]
<img width="468" alt="screenshot 2015-12-26 09 45 06" src="https://cloud.githubusercontent.com/assets/1167712/12007357/64d97c48-abb5-11e5-9b77-4421434a2f28.png">

Can confirm, `_modal` is indeed undefined if you never click on an image.  I can submit a pull request tonight, but I  think it's just going to include a:

`if (!_modal) return` to avoid calling `remove` if no `_modal` exists.

**Comment by pedroabreu** [comment]
Fixed with latest update

**Comment by ggoforth** [comment]
Can confirm, thanks @pedroabreu!
