### ISSUE TITLE
UI not updating on adding more items to array

### ISSUE THREAD

**Issue by illavirs** [pedroabreu/ion-gallery#3]
When I initialize the items array with values eg { src: ' .. ' } it displays fine, but when I add more items to the array later via javascript, UI is not getting updated. Its still displaying the initialized values.

**Comment by pedroabreu** [comment]
I'll have a look at this. First thing that comes to mind is that the scope value is not updated (Probably have to force it with a timeout)

**Comment by pedroabreu** [comment]
Fixed in latest commit
