### ISSUE TITLE
DIsable "Zoom" effect on iOS

### ISSUE THREAD

**Issue by b3na** [pedroabreu/ion-gallery#34]
I have noticed that on iOS when the pictures appear, there is a little "zooming"effect on each one, but that is not happening on Android. 

![Zoom effect](https://media.giphy.com/media/fZBj0TySIYSxa/giphy.gif)

Is there a way to disable this effect? 

PS.- I think the effect looks cool, but my client doesn't like it :crying_cat_face:

**Comment by pedroabreu** [comment]
I've never seen this effect before, what version of iOS is this ?

**Comment by pedroabreu** [comment]
Can't reproduce it

**Comment by ezazwar1** [comment]
most probably he is using animate.css
