### ISSUE TITLE
Zoom flickering - Disable zoom?

### ISSUE THREAD

**Issue by mladenp** [pedroabreu/ion-gallery#37]
There is some weird flickering in header when zooming images. 
Also i don't need zooming, is there a way to disable it?

**Comment by pedroabreu** [comment]
There is no way to disable zoom for now. It can actually be an interesting feature to add, with some sort of flag on the configProvider

**Comment by mladenp** [comment]
I tried disabling it by renaming your zoom events but it doesn't work for some reason, i didn't go deeper into code. 
Can you suggest how to quickly disable zoom for now and i'll try to figure out the flickering later if i have time.

**Comment by pedroabreu** [comment]
#55 is an initial implementation for this feature

**Comment by pedroabreu** [comment]
Merged
