### ISSUE TITLE
Adding buttons to the ion-gallery

### ISSUE THREAD

**Issue by dramzig** [pedroabreu/ion-gallery#46]
Hi,
First of all, thanks @pedroabreu for this great plugin. Very useful!

I want to add more buttons next to "close", for example, "share", "delete", "use it", or so.. I was trying to create the buttons on the template, pass the scope passing the scope to the directive and create functions for every button on the controller, but I didnt success. I dont even know if this is the best way to do it.

I'm not an expert and I need a little help. Does anyone have an example or some guidence to do this?

**Comment by pedroabreu** [comment]
Can you show me how far you've got ?

You need to edit `ion-gallery/src/templates/slider.html` and after that build with `gulp`

**Comment by pedroabreu** [comment]
Same as #19
