### ISSUE TITLE
Consider using ion-sildes

### ISSUE THREAD

**Issue by vhoxha08** [pedroabreu/ion-gallery#47]
Since `<ion-slide-box>` is deprecated in the new versions and will be removed in the future in favor of the new `<ion-slides>` perhaps you should consider doing the same. The gallery works just fine as it is, but `<ion-slides>` has a lot more configuration options, and will have continuous support in the future.

**Comment by pedroabreu** [comment]
I've seen they will deprecate it and I've been meaning to have a look at it but my dev environment went crazy.
Any news of when are they planning to cut support to it ?

**Comment by vhoxha08** [comment]
Not to worry, they just deprecated it so i think it will remain for some time, at least the next 4-5 releases. Good luck with your dev environment.
