### ISSUE TITLE
Change background slider color to black

### ISSUE THREAD

**Issue by ghchia** [pedroabreu/ion-gallery#5]
When I tested my application, the background color of the slider is either light grey or white. I am trying to change it to black (same as the demo image).

I tried to add '! important' to .imageView and also change background color of .gallery-slide-view to black in the css but they didn't work. 

I am not sure if it is an CSS or js issue. Would you be able to advise on this? Thanks.

**Comment by pedroabreu** [comment]
It seems to me that it's a css issue. Can you inspect your app and check what style is being rendered ? Maybe some other style you have is overriding it. If so, I need to think in some sort of closure for the styles, unless you specifically want to change the style

**Comment by ghchia** [comment]
The style rendered was .slider-slide. 

I added the following to the ionic.app.scss and the background is changed to black.

.slider-slide {
 background-color: black !important;
}

Thank you for your pointer.

**Comment by pedroabreu** [comment]
Fixed on version v0.1.6 .

I changed the background color definition to the listContainer class. Don't like to define it on classes where I don't have "control"
