### ISSUE TITLE
Its not issue but request to add ionic image lazy load plugin in this plugin

### ISSUE THREAD

**Issue by nabinkumarn** [pedroabreu/ion-gallery#58]
Can you add the ionic image lazy load plugin to this plugin? It would be the best.

**Comment by pedroabreu** [comment]
You can implement your own lazy loading (Or a similar version of it). The directive updates every time there's changes on the item array. So if you implement some sort of scroll listener, you can push more images to the array which will make it update and show the new images.

I don't think it's a good idea to implement another directive on top of this one. To be honest, the least dependencies it has, the better.

**Comment by nabinkumarn** [comment]
Thanks for the reply. I am new to angular and not good at directives. I liked the ionic gallery and am using it. I tried to change your directive to get lazy loading for images but was not able to do so. If I have to implement image lazy load I have to remove this gallery directive to do so which I don't want to. I got lazy load with some jquery code also but could not integrate it in this galley directive. If you can help :)

**Comment by pedroabreu** [comment]
Should be implemented outside the directive
