### ISSUE TITLE
Embedding Custom Link

### ISSUE THREAD

**Issue by artwaniparas** [pedroabreu/ion-gallery#65]
I want to make an application where a link would be displayed with every image in modal window . On clicking it another page should open which will have details on that image? Can you please guide how to implement it

**Comment by pedroabreu** [comment]
From the top of my head, you can pass a link to the subtitle and work from there. More help than that, just by changing the source to trigger a difference action on tap on the image

**Comment by artwaniparas** [comment]
That comes very hand, thanks. I tried putting the link in subtitle in the below format 

`sub: '<a href=#/app/playlists/3>Divine Jewel</a>'`

but now I think, I am not able to understand how to pass a unique value for every image, for example in above code,3 is passed with first image..

**Comment by pedroabreu** [comment]
You just need to construct the content of sub for every image and pass it to the directive
