### ISSUE TITLE
Grid Image Height in Modal

### ISSUE THREAD

**Issue by nmckeown** [pedroabreu/ion-gallery#75]
Hi pedroabreu/users,

I really like your plug-in and hoping to use it. I am loading the gallery in a modal. My issue is in the gallery grid, there is only a strip visible across the middle of the picture. I'm not strong in CSS so struggling to fix it. Appreciate any help and thanks for sharing, awesome work. I have included a screen cap of what I'm observing.

![untitled](https://cloud.githubusercontent.com/assets/5637532/20948348/9834a3b2-bc0b-11e6-8f24-24cbbf226719.png)

![image](https://cloud.githubusercontent.com/assets/5637532/20948420/fd8fae14-bc0b-11e6-8aa8-75b49e1dae43.png)

**Comment by nmckeown** [comment]
I have resolved this. I think it was problem with the structure of my array.

**Comment by pedroabreu** [comment]
Great 👍

**Comment by felipelopes6** [comment]
how do you fixed it? @nmckeown ?

**Comment by felipelopes6** [comment]
![screen shot 2017-08-21 at 09 44 01](https://user-images.githubusercontent.com/2061772/29519860-4ac8b36a-8655-11e7-9d25-d00400c07ef6.png)


I have the same issue!
