### ISSUE TITLE
gallery on ionicModal

### ISSUE THREAD

**Issue by crmolinaz** [pedroabreu/ion-gallery#8]
Hi, i found a problem when i tried to put the gallery into an ionicModal. The problem is that gallery don't show the pictures because no can estimated the height for the parent row.

**Comment by pedroabreu** [comment]
My first guess would be that it's not able to calculate element[0].offsetWidth because the element is not yet on the DOM.
But I'll give it a go and see if I can make it work on a modal

**Comment by crmolinaz** [comment]
i understand. But i observed that only happens at the second time. When i open the modal just once, all going ok.

**Comment by pedroabreu** [comment]
Could be that the destroy of the modal you're creating. It would them make sense for it to fail.
Do you have any test project I can play with ?

**Comment by pedroabreu** [comment]
Fixed

**Comment by CarsonChen1129** [comment]
Hi, I have the same problem as OP. The height for row and the image is 0px in the Modal. How can I fix it? Thank you very much in advance.

**Comment by pedroabreu** [comment]
Can you inspect and check if the image is being loaded ? Are you trying to load the gallery inside a modal ?

**Comment by CarsonChen1129** [comment]
Hello Pedro, thank you very much for the quick response. Yes, I am trying to load the gallery inside a modal, the images are being loaded without problems but just very tiny, I tried to change the css but nothing happens. So right now it looks like this.
<img width="386" alt="screen shot 2016-03-31 at 2 44 23 pm" src="https://cloud.githubusercontent.com/assets/3538333/14187022/2473ed2e-f74f-11e5-91b9-82b526869b73.png">
